server:
  port : 8080

spring:
  application:
    name : msvc-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: lb://msvc-student
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: lb://msvc-course
          predicates:
            - Path=/api/course/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8099/realms/microservices-realm

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

